language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t olagunju/docker-react  .

script:
  - docker run -e CI=true olagunju/docker-react

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-358242627487"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
